# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inp_cpp <- function(x, y, argval) {
    .Call(`_FunTest_inp_cpp`, x, y, argval)
}

inp_matrix <- function(V, argval) {
    .Call(`_FunTest_inp_matrix`, V, argval)
}

l2norm_cpp <- function(x) {
    .Call(`_FunTest_l2norm_cpp`, x)
}

ker_phi1_cpp <- function(x, y) {
    .Call(`_FunTest_ker_phi1_cpp`, x, y)
}

ker_log_cpp <- function(x, y) {
    .Call(`_FunTest_ker_log_cpp`, x, y)
}

ker_exp_cpp <- function(x, y) {
    .Call(`_FunTest_ker_exp_cpp`, x, y)
}

Gram_matrix_cpp_phi1 <- function(x) {
    .Call(`_FunTest_Gram_matrix_cpp_phi1`, x)
}

Gram_matrix_cpp_exp <- function(x) {
    .Call(`_FunTest_Gram_matrix_cpp_exp`, x)
}

Gram_matrix_cpp_log <- function(x) {
    .Call(`_FunTest_Gram_matrix_cpp_log`, x)
}

Gram_calc_phi1 <- function(S) {
    .Call(`_FunTest_Gram_calc_phi1`, S)
}

Gram_calc_exp <- function(S) {
    .Call(`_FunTest_Gram_calc_exp`, S)
}

Gram_calc_log <- function(S) {
    .Call(`_FunTest_Gram_calc_log`, S)
}

kmmd_cpp <- function(D, n, m) {
    .Call(`_FunTest_kmmd_cpp`, D, n, m)
}

test <- function(M, ind) {
    .Call(`_FunTest_test`, M, ind)
}

op1 <- function(L, l, n, m) {
    .Call(`_FunTest_op1`, L, l, n, m)
}

T_perm <- function(W, L, n, m) {
    .Call(`_FunTest_T_perm`, W, L, n, m)
}

inp <- function(x, y, time) {
    .Call(`_FunTest_inp`, x, y, time)
}

median_huristic <- function(list, time) {
    .Call(`_FunTest_median_huristic`, list, time)
}

median_huristic_2 <- function(list, time) {
    .Call(`_FunTest_median_huristic_2`, list, time)
}

proj_cpp <- function(x, argval) {
    .Call(`_FunTest_proj_cpp`, x, argval)
}

perm <- function(n) {
    .Call(`_FunTest_perm`, n)
}

summat <- function(A) {
    .Call(`_FunTest_summat`, A)
}

sumvec <- function(A) {
    .Call(`_FunTest_sumvec`, A)
}

colSum_cpp <- function(A) {
    .Call(`_FunTest_colSum_cpp`, A)
}

operation1 <- function(l, A) {
    .Call(`_FunTest_operation1`, l, A)
}

operation2 <- function(l, A) {
    .Call(`_FunTest_operation2`, l, A)
}

g_cpp <- function(K) {
    .Call(`_FunTest_g_cpp`, K)
}

gaussian_kernel <- function(x, b) {
    .Call(`_FunTest_gaussian_kernel`, x, b)
}

stat <- function(D, b) {
    .Call(`_FunTest_stat`, D, b)
}

stat_2 <- function(D, b) {
    .Call(`_FunTest_stat_2`, D, b)
}

rowcolsam <- function(A) {
    .Call(`_FunTest_rowcolsam`, A)
}

permutation <- function(D, R, b) {
    .Call(`_FunTest_permutation`, D, R, b)
}

permutation_2 <- function(D, R, b) {
    .Call(`_FunTest_permutation_2`, D, R, b)
}

multi_permutation <- function(D, R, b) {
    .Call(`_FunTest_multi_permutation`, D, R, b)
}

multi_permutation_2 <- function(D, R, b) {
    .Call(`_FunTest_multi_permutation_2`, D, R, b)
}

