# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inp <- function(x, y, time) {
    .Call(`_FunTest_inp`, x, y, time)
}

median_huristic <- function(list, time) {
    .Call(`_FunTest_median_huristic`, list, time)
}

median_huristic_2 <- function(list, time) {
    .Call(`_FunTest_median_huristic_2`, list, time)
}

proj_cpp <- function(x, argval) {
    .Call(`_FunTest_proj_cpp`, x, argval)
}

perm <- function(n) {
    .Call(`_FunTest_perm`, n)
}

summat <- function(A) {
    .Call(`_FunTest_summat`, A)
}

sumvec <- function(A) {
    .Call(`_FunTest_sumvec`, A)
}

colSum_cpp <- function(A) {
    .Call(`_FunTest_colSum_cpp`, A)
}

operation1 <- function(l, A) {
    .Call(`_FunTest_operation1`, l, A)
}

operation2 <- function(l, A) {
    .Call(`_FunTest_operation2`, l, A)
}

g_cpp <- function(K) {
    .Call(`_FunTest_g_cpp`, K)
}

gaussian_kernel <- function(x, b) {
    .Call(`_FunTest_gaussian_kernel`, x, b)
}

stat <- function(D, b) {
    .Call(`_FunTest_stat`, D, b)
}

stat_2 <- function(D, b) {
    .Call(`_FunTest_stat_2`, D, b)
}

rowcolsam <- function(A) {
    .Call(`_FunTest_rowcolsam`, A)
}

permutation <- function(D, R, b) {
    .Call(`_FunTest_permutation`, D, R, b)
}

permutation_2 <- function(D, R, b) {
    .Call(`_FunTest_permutation_2`, D, R, b)
}

multi_permutation <- function(D, R, b) {
    .Call(`_FunTest_multi_permutation`, D, R, b)
}

